using System;
using System.Linq;
using Tag.Vows.Web;
using model;

//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//    生成时间: 2016年04月18日 22:19:44。
//    应避免手动更改此文件。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
/*  Powered by VowsTag http://git.oschina.net/ichynul/vowstag/wikis/home  */

public partial class Page_index : xx.yy.PageBase
       /*重新指定了页面处理类，请确保 xx.yy.PageBase 直接或间接继承自'Tag.Vows.Web.TagPage'*/
{
    protected void Page_Load(object sender, EventArgs e)
    {
        if (!this.IsPostBack)
        {
            if (this.Befor_Load_Tags())
            {
                Load_LabelTag_16294_3();
                Bind_ListTag_67534_5();
            }
        }
    }

    public void Load_LabelTag_16294_3()
    {
        SubControl uc_label=(SubControl) LoadControl( "notice.ascx");
        uc_label.SetDb(this.Db_Context);
        uc_label.SetConfig(this.config);
        LabelTag_16294_3.Controls.Add(uc_label);
    }

    public void Bind_ListTag_67534_5()
    {
        /*orderby=id&desc=true&take=99&item=artiel_by_categ*/
        var list = from a in Db_Context.Category
                    select a;
        int totalsize = list.Count();
        list = list.OrderByDescending(c=>c.ID).Take(99);
        /*不分页，显示前 99条数据;*/
        if (list.Count() == 0)
        {
            empty_ListTag_67534_5.Text = "<div class='emptydiv'><span class='emptytext'>暂无内容</span></div>";
            return;
        }
        foreach(Category item in list)
        {
            SubControl uc_item=(SubControl) LoadControl( "artiel_by_categ.ascx");
            uc_item.SetItem(item);
            uc_item.SetDb(this.Db_Context);
            uc_item.SetConfig(this.config);
            ListTag_67534_5.Controls.Add(uc_item);
        }
    }


    private Entities _Db_Context;
    protected Entities Db_Context
    {
        get
        {
            if (_Db_Context == null)
            {
                _Db_Context = new Entities();
            }
            return _Db_Context;
        }
    }

    protected override object GetDbObject()
    {
        return this.Db_Context;
    }
}